package com.hermanowicz.pantry.db.product;

import org.junit.Before;
import androidx.test.core.app.ApplicationProvider;
import org.junit.Test;

public class Test106 {

    /**
     * Generated from /scratch/berreiter/action-based-test-carving/apps-src/MyPantry/traces/activities.MyPantryActivityTest#onClickOnEditProductInProductDetailsShouldNavigateToEditProductActivity/Trace-1659559113343.txt
     * Method invocation under test: <com.hermanowicz.pantry.db.product.Product: int getId()>_2457_4912
     */
    @Test(timeout = 4000)
    public void test_com_hermanowicz_pantry_db_product_Product_getId_001() throws Exception {
        com.hermanowicz.pantry.db.product.Product product65 = null;
        product65 = new com.hermanowicz.pantry.db.product.Product();
        product65.setId(1);
        product65.setName("Raspberry juice");
        product65.setHashCode("147263543");
        product65.setTypeOfProduct("Fruits");
        product65.setProductFeatures("Syrup");
        product65.setStorageLocation("");
        product65.setExpirationDate("2020-01-01");
        product65.setProductionDate("2019-12-31");
        product65.setComposition("Raspberries");
        product65.setHealingProperties("");
        product65.setDosage("Much");
        product65.setVolume(500);
        product65.setWeight(1000);
        product65.setHasSugar(true);
        product65.setHasSalt(false);
        product65.setIsVege(false);
        product65.setIsBio(false);
        product65.setTaste("Sweet");
        product65.setPhotoName("");
        product65.setPhotoDescription("");
        product65.setBarcode("");
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getName();
        product65.getExpirationDate();
        product65.getProductFeatures();
        product65.getComposition();
        product65.getHealingProperties();
        product65.getDosage();
        product65.getVolume();
        product65.getWeight();
        product65.getTypeOfProduct();
        product65.getProductFeatures();
        product65.getHasSalt();
        product65.getHasSugar();
        product65.getIsBio();
        product65.getIsVege();
        product65.getBarcode();
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getTaste();
        product65.getName();
        product65.getExpirationDate();
        product65.getProductFeatures();
        product65.getComposition();
        product65.getHealingProperties();
        product65.getDosage();
        product65.getVolume();
        product65.getWeight();
        product65.getTypeOfProduct();
        product65.getProductFeatures();
        product65.getHasSalt();
        product65.getHasSugar();
        product65.getIsBio();
        product65.getIsVege();
        product65.getBarcode();
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getTaste();
        product65.getName();
        product65.getName();
        product65.getName();
        product65.getName();
        product65.getName();
        product65.getName();
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getName();
        product65.getExpirationDate();
        product65.getProductFeatures();
        product65.getComposition();
        product65.getHealingProperties();
        product65.getDosage();
        product65.getVolume();
        product65.getWeight();
        product65.getTypeOfProduct();
        product65.getProductFeatures();
        product65.getHasSalt();
        product65.getHasSugar();
        product65.getIsBio();
        product65.getIsVege();
        product65.getBarcode();
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getTaste();
        product65.getName();
        product65.getExpirationDate();
        product65.getProductFeatures();
        product65.getComposition();
        product65.getHealingProperties();
        product65.getDosage();
        product65.getVolume();
        product65.getWeight();
        product65.getTypeOfProduct();
        product65.getProductFeatures();
        product65.getHasSalt();
        product65.getHasSugar();
        product65.getIsBio();
        product65.getIsVege();
        product65.getBarcode();
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getTaste();
        product65.getName();
        product65.getName();
        product65.getName();
        product65.getName();
        product65.getName();
        product65.getName();
        product65.getWeight();
        product65.getVolume();
        product65.getShortName();
        product65.getHasSugar();
        product65.getHasSalt();
        product65.getIsVege();
        product65.getIsBio();
        product65.getExpirationDate();
        product65.getExpirationDate();
        product65.getExpirationDate();
        product65.getExpirationDate();
        product65.getId();
    }
}
