package com.hermanowicz.pantry.db.product;

import org.junit.Before;
import androidx.test.core.app.ApplicationProvider;
import org.junit.Test;

public class Test1175 {

    /**
     * Generated from /scratch/berreiter/action-based-test-carving/apps-src/MyPantry/traces/activities.MyPantryActivityTest#onClickOnItemInRecyclerViewNavigateToProductDetailsActivity/Trace-1659559083578.txt
     * Method invocation under test: <com.hermanowicz.pantry.db.product.Product: java.lang.String getHashCode()>_2462_4922
     */
    @Test(timeout = 4000)
    public void test_com_hermanowicz_pantry_db_product_Product_getHashCode_001() throws Exception {
        com.hermanowicz.pantry.db.product.Product product66 = null;
        product66 = new com.hermanowicz.pantry.db.product.Product();
        product66.setId(3);
        product66.setName("Tomato");
        product66.setHashCode("235983629");
        product66.setTypeOfProduct("Vegetables");
        product66.setProductFeatures("Compote");
        product66.setStorageLocation("");
        product66.setExpirationDate("2021-07-12");
        product66.setProductionDate("2018-12-10");
        product66.setComposition("");
        product66.setHealingProperties("");
        product66.setDosage("");
        product66.setVolume(400);
        product66.setWeight(5000);
        product66.setHasSugar(false);
        product66.setHasSalt(false);
        product66.setIsVege(false);
        product66.setIsBio(false);
        product66.setTaste("");
        product66.setPhotoName("");
        product66.setPhotoDescription("");
        product66.setBarcode("");
        product66.getPhotoName();
        product66.getPhotoDescription();
        product66.getName();
        product66.getName();
        product66.getExpirationDate();
        product66.getProductFeatures();
        product66.getComposition();
        product66.getHealingProperties();
        product66.getDosage();
        product66.getVolume();
        product66.getWeight();
        product66.getTypeOfProduct();
        product66.getProductFeatures();
        product66.getHasSalt();
        product66.getHasSugar();
        product66.getIsBio();
        product66.getIsVege();
        product66.getBarcode();
        product66.getPhotoName();
        product66.getPhotoDescription();
        product66.getTaste();
        product66.getName();
        product66.getExpirationDate();
        product66.getProductFeatures();
        product66.getComposition();
        product66.getHealingProperties();
        product66.getDosage();
        product66.getVolume();
        product66.getWeight();
        product66.getTypeOfProduct();
        product66.getProductFeatures();
        product66.getHasSalt();
        product66.getHasSugar();
        product66.getIsBio();
        product66.getIsVege();
        product66.getBarcode();
        product66.getPhotoName();
        product66.getPhotoDescription();
        product66.getTaste();
        product66.getName();
        product66.getName();
        product66.getName();
        product66.getPhotoName();
        product66.getPhotoDescription();
        product66.getName();
        product66.getName();
        product66.getExpirationDate();
        product66.getProductFeatures();
        product66.getComposition();
        product66.getHealingProperties();
        product66.getDosage();
        product66.getVolume();
        product66.getWeight();
        product66.getTypeOfProduct();
        product66.getProductFeatures();
        product66.getHasSalt();
        product66.getHasSugar();
        product66.getIsBio();
        product66.getIsVege();
        product66.getBarcode();
        product66.getPhotoName();
        product66.getPhotoDescription();
        product66.getTaste();
        product66.getName();
        product66.getExpirationDate();
        product66.getProductFeatures();
        product66.getComposition();
        product66.getHealingProperties();
        product66.getDosage();
        product66.getVolume();
        product66.getWeight();
        product66.getTypeOfProduct();
        product66.getProductFeatures();
        product66.getHasSalt();
        product66.getHasSugar();
        product66.getIsBio();
        product66.getIsVege();
        product66.getBarcode();
        product66.getPhotoName();
        product66.getPhotoDescription();
        product66.getTaste();
        product66.getName();
        product66.getName();
        product66.getName();
        product66.getWeight();
        product66.getVolume();
        product66.getShortName();
        product66.getHasSugar();
        product66.getHasSalt();
        product66.getIsVege();
        product66.getIsBio();
        product66.getExpirationDate();
        product66.getExpirationDate();
        product66.getExpirationDate();
        product66.getExpirationDate();
        product66.getId();
        product66.getHashCode();
    }
}
