package com.hermanowicz.pantry.db.product;

import org.junit.Before;
import androidx.test.core.app.ApplicationProvider;
import org.junit.Test;

public class Test1174 {

    /**
     * Generated from /scratch/berreiter/action-based-test-carving/apps-src/MyPantry/traces/activities.MyPantryActivityTest#onClickOnItemInRecyclerViewNavigateToProductDetailsActivity/Trace-1659559083578.txt
     * Method invocation under test: <com.hermanowicz.pantry.db.product.Product: int getId()>_2457_4912
     */
    @Test(timeout = 4000)
    public void test_com_hermanowicz_pantry_db_product_Product_getId_001() throws Exception {
        com.hermanowicz.pantry.db.product.Product product65 = null;
        product65 = new com.hermanowicz.pantry.db.product.Product();
        product65.setId(3);
        product65.setName("Tomato");
        product65.setHashCode("235983629");
        product65.setTypeOfProduct("Vegetables");
        product65.setProductFeatures("Compote");
        product65.setStorageLocation("");
        product65.setExpirationDate("2021-07-12");
        product65.setProductionDate("2018-12-10");
        product65.setComposition("");
        product65.setHealingProperties("");
        product65.setDosage("");
        product65.setVolume(400);
        product65.setWeight(5000);
        product65.setHasSugar(false);
        product65.setHasSalt(false);
        product65.setIsVege(false);
        product65.setIsBio(false);
        product65.setTaste("");
        product65.setPhotoName("");
        product65.setPhotoDescription("");
        product65.setBarcode("");
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getName();
        product65.getName();
        product65.getExpirationDate();
        product65.getProductFeatures();
        product65.getComposition();
        product65.getHealingProperties();
        product65.getDosage();
        product65.getVolume();
        product65.getWeight();
        product65.getTypeOfProduct();
        product65.getProductFeatures();
        product65.getHasSalt();
        product65.getHasSugar();
        product65.getIsBio();
        product65.getIsVege();
        product65.getBarcode();
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getTaste();
        product65.getName();
        product65.getExpirationDate();
        product65.getProductFeatures();
        product65.getComposition();
        product65.getHealingProperties();
        product65.getDosage();
        product65.getVolume();
        product65.getWeight();
        product65.getTypeOfProduct();
        product65.getProductFeatures();
        product65.getHasSalt();
        product65.getHasSugar();
        product65.getIsBio();
        product65.getIsVege();
        product65.getBarcode();
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getTaste();
        product65.getName();
        product65.getName();
        product65.getName();
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getName();
        product65.getName();
        product65.getExpirationDate();
        product65.getProductFeatures();
        product65.getComposition();
        product65.getHealingProperties();
        product65.getDosage();
        product65.getVolume();
        product65.getWeight();
        product65.getTypeOfProduct();
        product65.getProductFeatures();
        product65.getHasSalt();
        product65.getHasSugar();
        product65.getIsBio();
        product65.getIsVege();
        product65.getBarcode();
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getTaste();
        product65.getName();
        product65.getExpirationDate();
        product65.getProductFeatures();
        product65.getComposition();
        product65.getHealingProperties();
        product65.getDosage();
        product65.getVolume();
        product65.getWeight();
        product65.getTypeOfProduct();
        product65.getProductFeatures();
        product65.getHasSalt();
        product65.getHasSugar();
        product65.getIsBio();
        product65.getIsVege();
        product65.getBarcode();
        product65.getPhotoName();
        product65.getPhotoDescription();
        product65.getTaste();
        product65.getName();
        product65.getName();
        product65.getName();
        product65.getWeight();
        product65.getVolume();
        product65.getShortName();
        product65.getHasSugar();
        product65.getHasSalt();
        product65.getIsVege();
        product65.getIsBio();
        product65.getExpirationDate();
        product65.getExpirationDate();
        product65.getExpirationDate();
        product65.getExpirationDate();
        product65.getId();
    }
}
