package com.hermanowicz.pantry.db.product;

import org.junit.Before;
import androidx.test.core.app.ApplicationProvider;
import org.junit.Test;

public class Test259 {

    /**
     * Generated from /scratch/berreiter/action-based-test-carving/apps-src/MyPantry/traces/activities.MyPantryActivityTest#onSetNameFilterShouldShowProductsWithThisName/Trace-1659559133917.txt
     * Method invocation under test: <com.hermanowicz.pantry.db.product.Product: java.lang.String getProductionDate()>_2546_5084
     */
    @Test(timeout = 4000)
    public void test_com_hermanowicz_pantry_db_product_Product_getProductionDate_001() throws Exception {
        com.hermanowicz.pantry.db.product.Product product74 = null;
        product74 = new com.hermanowicz.pantry.db.product.Product();
        product74.setId(1);
        product74.setName("Raspberry juice");
        product74.setHashCode("169851196");
        product74.setTypeOfProduct("Fruits");
        product74.setProductFeatures("Syrup");
        product74.setStorageLocation("");
        product74.setExpirationDate("2020-01-01");
        product74.setProductionDate("2019-12-31");
        product74.setComposition("Raspberries");
        product74.setHealingProperties("");
        product74.setDosage("Much");
        product74.setVolume(500);
        product74.setWeight(1000);
        product74.setHasSugar(true);
        product74.setHasSalt(false);
        product74.setIsVege(false);
        product74.setIsBio(false);
        product74.setTaste("Sweet");
        product74.setPhotoName("");
        product74.setPhotoDescription("");
        product74.setBarcode("");
        product74.getPhotoName();
        product74.getPhotoDescription();
        product74.getName();
        product74.getExpirationDate();
        product74.getProductFeatures();
        product74.getComposition();
        product74.getHealingProperties();
        product74.getDosage();
        product74.getVolume();
        product74.getWeight();
        product74.getTypeOfProduct();
        product74.getProductFeatures();
        product74.getHasSalt();
        product74.getHasSugar();
        product74.getIsBio();
        product74.getIsVege();
        product74.getBarcode();
        product74.getPhotoName();
        product74.getPhotoDescription();
        product74.getTaste();
        product74.getName();
        product74.getExpirationDate();
        product74.getProductFeatures();
        product74.getComposition();
        product74.getHealingProperties();
        product74.getDosage();
        product74.getVolume();
        product74.getWeight();
        product74.getTypeOfProduct();
        product74.getProductFeatures();
        product74.getHasSalt();
        product74.getHasSugar();
        product74.getIsBio();
        product74.getIsVege();
        product74.getBarcode();
        product74.getPhotoName();
        product74.getPhotoDescription();
        product74.getTaste();
        product74.getName();
        product74.getName();
        product74.getName();
        product74.getName();
        product74.getName();
        product74.getName();
        product74.getPhotoName();
        product74.getPhotoDescription();
        product74.getName();
        product74.getExpirationDate();
        product74.getProductFeatures();
        product74.getComposition();
        product74.getHealingProperties();
        product74.getDosage();
        product74.getVolume();
        product74.getWeight();
        product74.getTypeOfProduct();
        product74.getProductFeatures();
        product74.getHasSalt();
        product74.getHasSugar();
        product74.getIsBio();
        product74.getIsVege();
        product74.getBarcode();
        product74.getPhotoName();
        product74.getPhotoDescription();
        product74.getTaste();
        product74.getName();
        product74.getExpirationDate();
        product74.getProductFeatures();
        product74.getComposition();
        product74.getHealingProperties();
        product74.getDosage();
        product74.getVolume();
        product74.getWeight();
        product74.getTypeOfProduct();
        product74.getProductFeatures();
        product74.getHasSalt();
        product74.getHasSugar();
        product74.getIsBio();
        product74.getIsVege();
        product74.getBarcode();
        product74.getPhotoName();
        product74.getPhotoDescription();
        product74.getTaste();
        product74.getName();
        product74.getName();
        product74.getName();
        product74.getName();
        product74.getName();
        product74.getName();
        product74.getWeight();
        product74.getVolume();
        product74.getShortName();
        product74.getHasSugar();
        product74.getHasSalt();
        product74.getIsVege();
        product74.getIsBio();
        product74.getExpirationDate();
        product74.getExpirationDate();
        product74.getExpirationDate();
        product74.getExpirationDate();
        product74.getName();
        product74.getTypeOfProduct();
        product74.getProductFeatures();
        product74.getExpirationDate();
        product74.getProductionDate();
    }
}
