package com.hermanowicz.pantry.db.product;

import org.junit.Before;
import androidx.test.core.app.ApplicationProvider;
import org.junit.Test;

public class Test480 {

    /**
     * Generated from /scratch/berreiter/action-based-test-carving/apps-src/MyPantry/traces/activities.MyPantryActivityTest#onSetWeightFilterShouldShowProductsWithThisName/Trace-1659559058464.txt
     * Method invocation under test: <com.hermanowicz.pantry.db.product.Product: java.lang.String getShortName()>_2140_4278
     */
    @Test(timeout = 4000)
    public void test_com_hermanowicz_pantry_db_product_Product_getShortName_001() throws Exception {
        com.hermanowicz.pantry.db.product.Product product64 = null;
        product64 = new com.hermanowicz.pantry.db.product.Product();
        product64.setId(1);
        product64.setName("Raspberry juice");
        product64.setHashCode("183454814");
        product64.setTypeOfProduct("Fruits");
        product64.setProductFeatures("Syrup");
        product64.setStorageLocation("");
        product64.setExpirationDate("2020-01-01");
        product64.setProductionDate("2019-12-31");
        product64.setComposition("Raspberries");
        product64.setHealingProperties("");
        product64.setDosage("Much");
        product64.setVolume(500);
        product64.setWeight(1000);
        product64.setHasSugar(true);
        product64.setHasSalt(false);
        product64.setIsVege(false);
        product64.setIsBio(false);
        product64.setTaste("Sweet");
        product64.setPhotoName("");
        product64.setPhotoDescription("");
        product64.setBarcode("");
        product64.getPhotoName();
        product64.getPhotoDescription();
        product64.getName();
        product64.getExpirationDate();
        product64.getProductFeatures();
        product64.getComposition();
        product64.getHealingProperties();
        product64.getDosage();
        product64.getVolume();
        product64.getWeight();
        product64.getTypeOfProduct();
        product64.getProductFeatures();
        product64.getHasSalt();
        product64.getHasSugar();
        product64.getIsBio();
        product64.getIsVege();
        product64.getBarcode();
        product64.getPhotoName();
        product64.getPhotoDescription();
        product64.getTaste();
        product64.getName();
        product64.getExpirationDate();
        product64.getProductFeatures();
        product64.getComposition();
        product64.getHealingProperties();
        product64.getDosage();
        product64.getVolume();
        product64.getWeight();
        product64.getTypeOfProduct();
        product64.getProductFeatures();
        product64.getHasSalt();
        product64.getHasSugar();
        product64.getIsBio();
        product64.getIsVege();
        product64.getBarcode();
        product64.getPhotoName();
        product64.getPhotoDescription();
        product64.getTaste();
        product64.getName();
        product64.getName();
        product64.getName();
        product64.getName();
        product64.getName();
        product64.getName();
        product64.getPhotoName();
        product64.getPhotoDescription();
        product64.getName();
        product64.getExpirationDate();
        product64.getProductFeatures();
        product64.getComposition();
        product64.getHealingProperties();
        product64.getDosage();
        product64.getVolume();
        product64.getWeight();
        product64.getTypeOfProduct();
        product64.getProductFeatures();
        product64.getHasSalt();
        product64.getHasSugar();
        product64.getIsBio();
        product64.getIsVege();
        product64.getBarcode();
        product64.getPhotoName();
        product64.getPhotoDescription();
        product64.getTaste();
        product64.getName();
        product64.getExpirationDate();
        product64.getProductFeatures();
        product64.getComposition();
        product64.getHealingProperties();
        product64.getDosage();
        product64.getVolume();
        product64.getWeight();
        product64.getTypeOfProduct();
        product64.getProductFeatures();
        product64.getHasSalt();
        product64.getHasSugar();
        product64.getIsBio();
        product64.getIsVege();
        product64.getBarcode();
        product64.getPhotoName();
        product64.getPhotoDescription();
        product64.getTaste();
        product64.getName();
        product64.getName();
        product64.getName();
        product64.getName();
        product64.getName();
        product64.getName();
        product64.getWeight();
        product64.getVolume();
        product64.getShortName();
    }
}
